package types

import (
	"go.mau.fi/mautrix-googlechat/pkg/gchatmeow/proto/gchatprotoweb"
)

type InitialConfigData struct {
	PageConfig  *MessagesPageConfig
	CurrentUser *gchatprotoweb.DynamiteGetSelf
	GroupList   *gchatprotoweb.DynamiteGetGroupList
}

type MessagesPageConfig struct {
	AB33Kc         string   `json:"AB33kc,omitempty"`
	AWKGrb         int      `json:"AWKGrb,omitempty"`
	BlSXl          int      `json:"BlSXl,omitempty"`
	CNJmhc         int      `json:"CNJmhc,omitempty"`
	CbgPzb         string   `json:"CbgPzb,omitempty"`
	DJ6CJf         bool     `json:"DJ6CJf,omitempty"`
	Didcob         string   `json:"Didcob,omitempty"`
	DpimGf         bool     `json:"DpimGf,omitempty"`
	EP1Ykd         []string `json:"EP1ykd,omitempty"`
	FNgocc         string   `json:"FNgocc,omitempty"`
	FdrFJe         string   `json:"FdrFJe,omitempty"`
	G3Mk3C         string   `json:"G3Mk3c,omitempty"`
	GDedOb         string   `json:"GDedOb,omitempty"`
	HwRqsf         string   `json:"HwRqsf,omitempty"`
	IPZ2Nf         string   `json:"IPZ2nf,omitempty"`
	NextPath       string   `json:"Im6cmf,omitempty"`
	JeBesf         string   `json:"JeBesf,omitempty"`
	KQzwo          string   `json:"KQzwo,omitempty"`
	LVIXXb         int      `json:"LVIXXb,omitempty"`
	LoQv7E         bool     `json:"LoQv7e,omitempty"`
	MT7F9B         []any    `json:"MT7f9b,omitempty"`
	MoAmce         int      `json:"MoAmce,omitempty"`
	N1Hiuc         int      `json:"N1hiuc,omitempty"`
	NBHKo          int      `json:"NBHKo,omitempty"`
	NH6GV          string   `json:"NH6gV,omitempty"`
	O39Xmb         string   `json:"O39xmb,omitempty"`
	Ozlfe          string   `json:"OZLFE,omitempty"`
	OumDo          int      `json:"OumDo,omitempty"`
	Pttpvd         string   `json:"Pttpvd,omitempty"`
	QrtxK          string   `json:"QrtxK,omitempty"`
	UserID         string   `json:"S06Grb,omitempty"`
	S6LZl          int      `json:"S6lZl,omitempty"`
	XSRFToken      string   `json:"SMqcke,omitempty"`
	SNlM0E         string   `json:"SNlM0e,omitempty"`
	SpaT4E         string   `json:"SpaT4e,omitempty"`
	T8TXce         string   `json:"T8TXce,omitempty"`
	TPDAuc         string   `json:"TPDAuc,omitempty"`
	TSDtV          string   `json:"TSDtV,omitempty"`
	XGoogleApiKey  string   `json:"Tzliq,omitempty"`
	U1P1Qc         string   `json:"U1p1Qc,omitempty"`
	Vvafkd         bool     `json:"Vvafkd,omitempty"`
	Vzc2Lb         string   `json:"Vzc2Lb,omitempty"`
	W3Yyqf         string   `json:"W3Yyqf,omitempty"`
	WZsZ1E         string   `json:"WZsZ1e,omitempty"`
	XkpsQc         string   `json:"XkpsQc,omitempty"`
	YVT37D         int      `json:"YVT37d,omitempty"`
	Yllh3E         string   `json:"Yllh3e,omitempty"`
	ZzF42C         string   `json:"ZzF42c,omitempty"`
	Bobt8D         string   `json:"bobt8d,omitempty"`
	C3JAdc         string   `json:"c3JAdc,omitempty"`
	Cfb2H          string   `json:"cfb2h,omitempty"`
	DXGpA          string   `json:"dXGpA,omitempty"`
	DfcQEd         string   `json:"dfcQEd,omitempty"`
	ENnkwf         string   `json:"eNnkwf,omitempty"`
	EQxUID         bool     `json:"eQxUid,omitempty"`
	EptZe          string   `json:"eptZe,omitempty"`
	FN988D         []int    `json:"fN988d,omitempty"`
	FPDxwd         []int    `json:"fPDxwd,omitempty"`
	G8Oz3D         string   `json:"g8Oz3d,omitempty"`
	GEq4Db         int      `json:"gEq4Db,omitempty"`
	GGcLoe         bool     `json:"gGcLoe,omitempty"`
	Hf8XYe         string   `json:"hf8xYe,omitempty"`
	ICzhFc         bool     `json:"iCzhFc,omitempty"`
	Jyy2Sb         string   `json:"jyy2sb,omitempty"`
	Khbx6E         bool     `json:"khbx6e,omitempty"`
	Lqu22B         string   `json:"lqu22b,omitempty"`
	MvGAmb         string   `json:"mvGAmb,omitempty"`
	NQyAE          NQyAE    `json:"nQyAE,omitempty"`
	UserEmail      string   `json:"oPEP7c,omitempty"`
	P9HQne         string   `json:"p9hQne,omitempty"`
	PDhDfb         bool     `json:"pDhDfb,omitempty"`
	PNTjBe         string   `json:"pNTjBe,omitempty"`
	QDCSke         string   `json:"qDCSke,omitempty"`
	QwAQke         string   `json:"qwAQke,omitempty"`
	QymVe          string   `json:"qymVe,omitempty"`
	RtQCxc         int      `json:"rtQCxc,omitempty"`
	RzXnhc         string   `json:"rzXnhc,omitempty"`
	Sas1Dd         string   `json:"sas1dd,omitempty"`
	Sp2Jnc         string   `json:"sp2Jnc,omitempty"`
	UoqGRe         string   `json:"uoqGRe,omitempty"`
	VLjptb         string   `json:"vLjptb,omitempty"`
	W2BtAe         string   `json:"w2btAe,omitempty"`
	WSDqhe         string   `json:"wSDqhe,omitempty"`
	XGoogleApiKey2 string   `json:"wU9aJb,omitempty"`
	WsqtJe         string   `json:"wsqtJe,omitempty"`
	Xn5OID         bool     `json:"xn5OId,omitempty"`
	Y2FhP          string   `json:"y2FhP,omitempty"`
	ZChJod         string   `json:"zChJod,omitempty"`
}

type NQyAE struct {
	D2PVxb string `json:"d2pVxb,omitempty"`
	YUoMqf string `json:"yUoMqf,omitempty"`
	FlXMi  string `json:"FlXMi,omitempty"`
	HTtJHb string `json:"HTtJHb,omitempty"`
	I3K3Mc string `json:"I3k3mc,omitempty"`
	PWpiXe string `json:"PWpiXe,omitempty"`
	Gw5UMe string `json:"Gw5uMe,omitempty"`
	BLMuMb string `json:"BLMuMb,omitempty"`
	Jwpqm  string `json:"JWPQM,omitempty"`
	F1W6Wd string `json:"F1W6Wd,omitempty"`
	JgQF1C string `json:"JgQF1c,omitempty"`
	S5WLJd string `json:"s5wLJd,omitempty"`
	YrMJbc string `json:"YrMJbc,omitempty"`
	LdZ6Ve string `json:"ldZ6ve,omitempty"`
	F3IUob string `json:"f3iUob,omitempty"`
	FQgVL  string `json:"FQgVL,omitempty"`
	Ek7Iw  string `json:"Ek7Iw,omitempty"`
	ROtCL  string `json:"rOtCL,omitempty"`
	EwmXEc string `json:"ewmXEc,omitempty"`
	GOuwSc string `json:"gOuwSc,omitempty"`
	VKIAjc string `json:"vKIAjc,omitempty"`
	RwbTSc string `json:"RwbTSc,omitempty"`
	WZHIQc string `json:"WZHIQc,omitempty"`
	AlNKyb string `json:"AlNKyb,omitempty"`
	OZ7Hjb string `json:"OZ7hjb,omitempty"`
	RO3M5  string `json:"rO3M5,omitempty"`
	Xbzdqb string `json:"xbzdqb,omitempty"`
	Hxvyye string `json:"Hxvyye,omitempty"`
	UlwQwc string `json:"ulwQwc,omitempty"`
	CCLr1E string `json:"CCLr1e,omitempty"`
	CDzBe  string `json:"CDzBe,omitempty"`
	H1Gzy  string `json:"h1gzy,omitempty"`
	Nym6O  string `json:"nym6O,omitempty"`
	Yc1M0  string `json:"yc1M0,omitempty"`
	XMpRPc string `json:"xMpRPc,omitempty"`
	PGLHIb string `json:"pGLHIb,omitempty"`
	ThhFw  string `json:"thhFw,omitempty"`
	MwiNGe string `json:"mwiNGe,omitempty"`
	OahUh  string `json:"OahUh,omitempty"`
	Fruypb string `json:"fruypb,omitempty"`
	XESand string `json:"xESand,omitempty"`
	JPEmzc string `json:"JPEmzc,omitempty"`
	IqiYxf string `json:"IqiYxf,omitempty"`
	FDGe6B string `json:"FDGe6b,omitempty"`
	Raugye string `json:"raugye,omitempty"`
	MqeEOd string `json:"MqeEOd,omitempty"`
	XJGTle string `json:"xJGTle,omitempty"`
	JJobRe string `json:"jJobRe,omitempty"`
	GWcc6B string `json:"gWcc6b,omitempty"`
	GWZQrb string `json:"GWZQrb,omitempty"`
	N1WJOe string `json:"n1WJOe,omitempty"`
	DplHib string `json:"DplHib,omitempty"`
	LkdIvd string `json:"LkdIvd,omitempty"`
	DYp3Yc string `json:"DYp3yc,omitempty"`
	ZqvInc string `json:"zqvInc,omitempty"`
	SOVNic string `json:"sOVNic,omitempty"`
	VuxmAd string `json:"VuxmAd,omitempty"`
	DzwJwb string `json:"dzwJwb,omitempty"`
	IJJUzd string `json:"iJJUzd,omitempty"`
	HLMP6D string `json:"hLMP6d,omitempty"`
	E0Drcf string `json:"e0drcf,omitempty"`
	TwDmFf string `json:"TwDmFf,omitempty"`
	Xm01Bb string `json:"xm01Bb,omitempty"`
	UnqpDd string `json:"UnqpDd,omitempty"`
	A9SONe string `json:"a9sONe,omitempty"`
	N3Getd string `json:"N3getd,omitempty"`
	KU59Ed string `json:"kU59ed,omitempty"`
	LriFyc string `json:"LriFyc,omitempty"`
	Ozsul  string `json:"Ozsul,omitempty"`
	CF0Mzb string `json:"CF0mzb,omitempty"`
	DA05Qf string `json:"dA05qf,omitempty"`
	W8Kj1  string `json:"W8Kj1,omitempty"`
	YuDFpc string `json:"YuDFpc,omitempty"`
	OLwM1B string `json:"oLwM1b,omitempty"`
	JBxQJc string `json:"jBxQJc,omitempty"`
	BTm3I  string `json:"bTm3I,omitempty"`
	YVsT9D string `json:"YVsT9d,omitempty"`
	Snwxzc string `json:"Snwxzc,omitempty"`
	UnoSW  string `json:"UnoSW,omitempty"`
	RH399E string `json:"rH399e,omitempty"`
	NJJwo  string `json:"nJJwo,omitempty"`
	V4Xwsd string `json:"V4Xwsd,omitempty"`
	KPEHac string `json:"KPEHac,omitempty"`
	GaZ1I  string `json:"GaZ1i,omitempty"`
	TkJRHd string `json:"TkJRHd,omitempty"`
	Fu7I6D string `json:"fu7I6d,omitempty"`
	AeMIPe string `json:"aeMIPe,omitempty"`
	N3Z7Ob string `json:"N3z7Ob,omitempty"`
	J7MHRc string `json:"j7mHRc,omitempty"`
	XEmPt  string `json:"XEmPt,omitempty"`
	IWA6Je string `json:"iWA6Je,omitempty"`
	IRL6Hc string `json:"IRL6Hc,omitempty"`
	I9TKb  string `json:"i9TKb,omitempty"`
	EidiL  string `json:"EidiL,omitempty"`
	N0HWk  string `json:"N0HWk,omitempty"`
	X9Oyzb string `json:"x9oyzb,omitempty"`
	DPt11  string `json:"dPt11,omitempty"`
	XdQReb string `json:"xdQReb,omitempty"`
	XxS7B  string `json:"XxS7b,omitempty"`
	XuCeWd string `json:"xuCeWd,omitempty"`
	LHlD6C string `json:"lHlD6c,omitempty"`
	Gh97Ec string `json:"gh97Ec,omitempty"`
	KNvFLb string `json:"KNvFLb,omitempty"`
	GjPG6C string `json:"GjPG6c,omitempty"`
	Om684B string `json:"om684b,omitempty"`
	WvY94B string `json:"wvY94b,omitempty"`
	WehTze string `json:"wehTze,omitempty"`
	FpAqdf string `json:"FpAqdf,omitempty"`
	J0DU0B string `json:"j0DU0b,omitempty"`
	F7X3D  string `json:"F7x3D,omitempty"`
	MBEPkc string `json:"mBEPkc,omitempty"`
	FFw7Rc string `json:"FFw7Rc,omitempty"`
	ZaK9Td string `json:"zaK9Td,omitempty"`
	NY4Jlb string `json:"nY4jlb,omitempty"`
	VlQmZd string `json:"VlQmZd,omitempty"`
	HuvGxf string `json:"HuvGxf,omitempty"`
	PM01Q  string `json:"PM01q,omitempty"`
	FttWhe string `json:"fttWhe,omitempty"`
	RSaU5  string `json:"rSaU5,omitempty"`
	HnOjkb string `json:"hnOjkb,omitempty"`
	NAX5Hc string `json:"NAX5hc,omitempty"`
	HP8EP  string `json:"hP8eP,omitempty"`
	Gtqkxd string `json:"Gtqkxd,omitempty"`
	UBHcPb string `json:"UBHcPb,omitempty"`
	QHuYrd string `json:"qHuYrd,omitempty"`
	SZ1Euf string `json:"SZ1euf,omitempty"`
	LNOwye string `json:"lNOwye,omitempty"`
	Vv8Erb string `json:"vv8Erb,omitempty"`
	XTb7N  string `json:"xTb7N,omitempty"`
	ZF0CBf string `json:"zF0cBf,omitempty"`
	OLs3Sb string `json:"OLs3sb,omitempty"`
	Rogcxe string `json:"rogcxe,omitempty"`
	BwRBs  string `json:"BwRBs,omitempty"`
	GEtEUd string `json:"gEtEUd,omitempty"`
	ASpTKc string `json:"aSpTKc,omitempty"`
	IS0Vpf string `json:"IS0vpf,omitempty"`
	FT5AAb string `json:"fT5AAb,omitempty"`
	O38Xyf string `json:"o38xyf,omitempty"`
	Rg0Ysf string `json:"rg0ysf,omitempty"`
	ZnY7R  string `json:"ZnY7R,omitempty"`
	TCZgY  string `json:"tCZgY,omitempty"`
	IrNUZc string `json:"IrNUZc,omitempty"`
	R7SeB  string `json:"R7seB,omitempty"`
	Ct0Xoe string `json:"Ct0Xoe,omitempty"`
	LrCvVb string `json:"lrCvVb,omitempty"`
	UNOEKc string `json:"UNOEKc,omitempty"`
	B8FMhf string `json:"b8fMhf,omitempty"`
	Vkaf8B string `json:"vkaf8b,omitempty"`
	CBBkmf string `json:"cBBkmf,omitempty"`
	Q6BNu  string `json:"Q6BNu,omitempty"`
	T2NQNe string `json:"T2NQNe,omitempty"`
	VzhPUc string `json:"vzhPUc,omitempty"`
	E0CSDb string `json:"E0CSDb,omitempty"`
	SJ6Gvc string `json:"sJ6Gvc,omitempty"`
	HdXQVb string `json:"hdXQVb,omitempty"`
	NCgwYe string `json:"NCgwYe,omitempty"`
	CK69K  string `json:"CK69k,omitempty"`
	ZkRaEc string `json:"zkRaEc,omitempty"`
	Md5Uwd string `json:"Md5uwd,omitempty"`
	FvBdYc string `json:"fvBdYc,omitempty"`
	S04KZc string `json:"s04KZc,omitempty"`
	RnB50E string `json:"RnB50e,omitempty"`
	Uq9L5  string `json:"uq9L5,omitempty"`
	FbR4Ff string `json:"fbR4Ff,omitempty"`
	HqJ2Ob string `json:"hqJ2ob,omitempty"`
	UI5N8  string `json:"ui5N8,omitempty"`
	DriAkf string `json:"driAkf,omitempty"`
	Pkuj8B string `json:"pkuj8b,omitempty"`
	E3JKWe string `json:"E3jKWe,omitempty"`
	FS9FQd string `json:"fS9FQd,omitempty"`
	DSnjAc string `json:"DSnjAc,omitempty"`
	PtUryc string `json:"PtUryc,omitempty"`
	QKT6Ed string `json:"QKT6ed,omitempty"`
	Bce8Nd string `json:"Bce8Nd,omitempty"`
	RfYgvf string `json:"rfYgvf,omitempty"`
	FRw9Jd string `json:"FRw9jd,omitempty"`
	Mlkmsd string `json:"Mlkmsd,omitempty"`
	HDnbib string `json:"HDnbib,omitempty"`
	P92TDc string `json:"p92tDc,omitempty"`
	Vpqnmc string `json:"vpqnmc,omitempty"`
	ZmUKzd string `json:"ZmUKzd,omitempty"`
	QKcgJd string `json:"qKcgJd,omitempty"`
	JARQh  string `json:"jARQh,omitempty"`
	AtaVwb string `json:"ataVwb,omitempty"`
	VaepD  string `json:"vaepD,omitempty"`
	Ulb7Ob string `json:"ulb7Ob,omitempty"`
	KGhXhd string `json:"KGhXhd,omitempty"`
	ZyDXDe string `json:"zyDXDe,omitempty"`
	EWApaf string `json:"EWApaf,omitempty"`
	BhCLWe string `json:"bhCLWe,omitempty"`
	WSkRQe string `json:"WSkRQe,omitempty"`
	J4RGre string `json:"J4rGre,omitempty"`
	P2YHQb string `json:"P2YHQb,omitempty"`
	NKqQFc string `json:"NKqQFc,omitempty"`
	JVysYe string `json:"jVysYe,omitempty"`
	S71P8E string `json:"s71p8e,omitempty"`
	MSEg4E string `json:"mSEg4e,omitempty"`
	VeuD8E string `json:"veuD8e,omitempty"`
	ORurxd string `json:"oRurxd,omitempty"`
	BcTJRe string `json:"bcTJRe,omitempty"`
	OfCC1B string `json:"OfCC1b,omitempty"`
	CoMAE  string `json:"coMAE,omitempty"`
	CO4Cde string `json:"CO4Cde,omitempty"`
	J1HbL  string `json:"j1HbL,omitempty"`
	X8LLPc string `json:"X8LLPc,omitempty"`
	FkHQY  string `json:"fkHQY,omitempty"`
	Tyi48E string `json:"Tyi48e,omitempty"`
	QhXqJd string `json:"QhXqJd,omitempty"`
	Iwz7Oe string `json:"iwz7Oe,omitempty"`
	YcXfQ  string `json:"YcXfQ,omitempty"`
	YfSz9  string `json:"YfSz9,omitempty"`
	MzlElc string `json:"mzlElc,omitempty"`
	KSt8Y  string `json:"kSt8Y,omitempty"`
	SJjLb  string `json:"SJjLb,omitempty"`
	VpIkze string `json:"VpIkze,omitempty"`
	SEYiZd string `json:"sEYiZd,omitempty"`
	H2Jigd string `json:"H2jigd,omitempty"`
	PLNzRe string `json:"PLNzRe,omitempty"`
	Zt6Ag  string `json:"zt6Ag,omitempty"`
	YRCbC  string `json:"YRCbC,omitempty"`
	H76ELb string `json:"h76eLb,omitempty"`
	Xg7LGb string `json:"xg7lGb,omitempty"`
	W0HJFc string `json:"W0HJFc,omitempty"`
	EMg2Ef string `json:"EMg2Ef,omitempty"`
	KiRBBc string `json:"KiRBBc,omitempty"`
	Ie16Xf string `json:"Ie16xf,omitempty"`
	RFGTUb string `json:"rFGTUb,omitempty"`
	J4ILJd string `json:"j4iLJd,omitempty"`
	FRhDfc string `json:"FRhDfc,omitempty"`
	C136Xe string `json:"C136xe,omitempty"`
	Ka1BDe string `json:"Ka1bDe,omitempty"`
	E2HX5D string `json:"E2hX5d,omitempty"`
	Wio0Kc string `json:"Wio0Kc,omitempty"`
	E8GFZe string `json:"e8GFZe,omitempty"`
	PDtAkb string `json:"PDtAkb,omitempty"`
	UgS6Se string `json:"UgS6se,omitempty"`
	P020U  string `json:"P020U,omitempty"`
	OHoHMb string `json:"oHoHMb,omitempty"`
	F8HUCb string `json:"f8hUCb,omitempty"`
	WRn1Hb string `json:"wRn1Hb,omitempty"`
	Jvkqqb string `json:"Jvkqqb,omitempty"`
	A0NDvb string `json:"a0nDvb,omitempty"`
	NvIy   string `json:"nvIy,omitempty"`
	Osj2O  string `json:"Osj2O,omitempty"`
	EsdAL  string `json:"EsdAL,omitempty"`
	SUkshb string `json:"sUkshb,omitempty"`
	OTseVd string `json:"OTseVd,omitempty"`
	Sr0UXc string `json:"Sr0UXc,omitempty"`
	Ps80We string `json:"Ps80we,omitempty"`
	ClefM  string `json:"ClefM,omitempty"`
	DBLDec string `json:"DBLDec,omitempty"`
	Ifl5Lb string `json:"ifl5Lb,omitempty"`
	UHZ16C string `json:"uHZ16c,omitempty"`
	CCE6Qb string `json:"cCE6Qb,omitempty"`
	PYmsLd string `json:"pYmsLd,omitempty"`
	MS6Trf string `json:"MS6Trf,omitempty"`
	WLyL4E string `json:"wLyL4e,omitempty"`
	PDKMdd string `json:"pDKMdd,omitempty"`
	JXbW4D string `json:"JXbW4d,omitempty"`
	Y9FXe  string `json:"y9FXe,omitempty"`
	HpGruc string `json:"hpGruc,omitempty"`
	IxVPDf string `json:"IxVPDf,omitempty"`
	RQ26Tc string `json:"rQ26tc,omitempty"`
	Y5Fxzd string `json:"Y5fxzd,omitempty"`
	ElFzcf string `json:"ElFzcf,omitempty"`
	DUWGN  string `json:"dUWGN,omitempty"`
	UAPzlb string `json:"UAPzlb,omitempty"`
	Nr0MWb string `json:"Nr0mWb,omitempty"`
	PyIX2  string `json:"PyIX2,omitempty"`
	Zg1Xjd string `json:"zg1xjd,omitempty"`
	EJccYe string `json:"eJccYe,omitempty"`
	Yt0JGd string `json:"yt0jGd,omitempty"`
	Osl51  string `json:"OSL51,omitempty"`
	XuZ9Od string `json:"xuZ9Od,omitempty"`
	U8Per  string `json:"u8Per,omitempty"`
	Jy5Zee string `json:"jy5zee,omitempty"`
	Mrbcef string `json:"Mrbcef,omitempty"`
	ZDduYd string `json:"zDduYd,omitempty"`
	NdLPff string `json:"NdLPff,omitempty"`
	K4CGJe string `json:"K4CGJe,omitempty"`
	CHKJLc string `json:"CHKJLc,omitempty"`
	Botc7C string `json:"Botc7c,omitempty"`
	QVhdlf string `json:"qVhdlf,omitempty"`
	DFRCsd string `json:"DFRCsd,omitempty"`
	HW1ZRc string `json:"HW1zRc,omitempty"`
	AQBVoe string `json:"AQBVoe,omitempty"`
	XxKBCb string `json:"xxKBCb,omitempty"`
	IKVpMb string `json:"IKVpMb,omitempty"`
	UXeYpb string `json:"uXeYpb,omitempty"`
	DjQuxd string `json:"djQuxd,omitempty"`
	AFLM7  string `json:"aFLM7,omitempty"`
	Qze8F  string `json:"qze8F,omitempty"`
	IHB6Rd string `json:"iHB6Rd,omitempty"`
	TJfatc string `json:"TJfatc,omitempty"`
	Tq1Yif string `json:"Tq1yif,omitempty"`
	OWr2T  string `json:"OWr2T,omitempty"`
	W47EW  string `json:"w47eW,omitempty"`
	EUNFHd string `json:"EUNFHd,omitempty"`
	Otpe0D string `json:"Otpe0d,omitempty"`
	YhL5Ic string `json:"yhL5ic,omitempty"`
	C8OW9  string `json:"c8oW9,omitempty"`
	WOYLMb string `json:"wOYLMb,omitempty"`
	YcE1Lc string `json:"ycE1lc,omitempty"`
	NE9Zrf string `json:"NE9zrf,omitempty"`
	Zpwl5B string `json:"Zpwl5b,omitempty"`
	DOMHb  string `json:"dOMHb,omitempty"`
	OTjV9B string `json:"OTjV9b,omitempty"`
	NWOO0C string `json:"nWOO0c,omitempty"`
	WYSsrc string `json:"wYSsrc,omitempty"`
	CuJ8Tb string `json:"CuJ8tb,omitempty"`
	J5MWTd string `json:"j5mWTd,omitempty"`
	WBmmtd string `json:"wBmmtd,omitempty"`
	I8FOxc string `json:"i8fOxc,omitempty"`
	F0LPte string `json:"f0lPte,omitempty"`
	XMEnSe string `json:"xMEnSe,omitempty"`
	S7PJlb string `json:"s7PJlb,omitempty"`
	TtQyZe string `json:"ttQyZe,omitempty"`
	Q37Rrc string `json:"q37rrc,omitempty"`
	H3XJGf string `json:"h3XJGf,omitempty"`
	F9USx  string `json:"F9uSx,omitempty"`
	DkY4E  string `json:"DkY4E,omitempty"`
	LMEL0C string `json:"lMEL0c,omitempty"`
	Rr7SUd string `json:"rr7sUd,omitempty"`
	LpnMIb string `json:"lpnMIb,omitempty"`
	JL5U4D string `json:"jL5u4d,omitempty"`
	Mcj6Ye string `json:"mcj6ye,omitempty"`
	EnuR5D string `json:"enuR5d,omitempty"`
	XDA8Ab string `json:"xDA8Ab,omitempty"`
	W5ATQb string `json:"W5ATQb,omitempty"`
	TBVkEe string `json:"TBVkEe,omitempty"`
	EPSUf  string `json:"EPSUf,omitempty"`
	Ey8Ksc string `json:"Ey8Ksc,omitempty"`
	SQZIne string `json:"sQZIne,omitempty"`
	Ij1Xjc string `json:"Ij1xjc,omitempty"`
	Yx4Xyb string `json:"yx4xyb,omitempty"`
	Nnyb3  string `json:"NNYB3,omitempty"`
	MTYEib string `json:"MTYEib,omitempty"`
	RdUSYd string `json:"rdUSYd,omitempty"`
	QbVQU  string `json:"qbVQU,omitempty"`
	UINZbe string `json:"uINZbe,omitempty"`
	WV48Oe string `json:"wV48oe,omitempty"`
	HhnOFf string `json:"hhnOFf,omitempty"`
	Wnr7Mc string `json:"Wnr7mc,omitempty"`
	SKl3Tf string `json:"SKl3tf,omitempty"`
	PdoRDb string `json:"PdoRDb,omitempty"`
	ZiGeBb string `json:"ZiGeBb,omitempty"`
	HGgKge string `json:"HGgKge,omitempty"`
	QC5FOc string `json:"qC5fOc,omitempty"`
	QiM0Fb string `json:"qiM0Fb,omitempty"`
	WqZfs  string `json:"WqZfs,omitempty"`
	BqsgTd string `json:"bqsgTd,omitempty"`
	DJegYc string `json:"DJegYc,omitempty"`
	PKEP   string `json:"pKEP,omitempty"`
	Qtz5H  string `json:"qtz5H,omitempty"`
	Z9GrYc string `json:"z9GrYc,omitempty"`
	HNl6Nb string `json:"hNl6nb,omitempty"`
	JkJP3D string `json:"jkJP3d,omitempty"`
	Qlh6Ee string `json:"Qlh6ee,omitempty"`
	QweLb  string `json:"qweLb,omitempty"`
	LC6R4D string `json:"LC6R4d,omitempty"`
	XmeGFd string `json:"xmeGFd,omitempty"`
	UvZcsc string `json:"UvZcsc,omitempty"`
	FzVrfe string `json:"fzVrfe,omitempty"`
	DYFpCd string `json:"dYFpCd,omitempty"`
	RKg7Re string `json:"RKg7re,omitempty"`
	D1Bn1B string `json:"D1bn1b,omitempty"`
}

type AFConfigKey string

const (
	DynamiteGetFeEmbedData      AFConfigKey = "ds:0"
	DynamiteGetGroupList        AFConfigKey = "ds:1"
	DynamiteGetUserSettings     AFConfigKey = "ds:2"
	DynamiteGetSelf             AFConfigKey = "ds:3"
	DynamiteGetBuildData        AFConfigKey = "ds:4"
	DynamiteGetClientParams     AFConfigKey = "ds:5"
	DynamiteGetBlockedUsersList AFConfigKey = "ds:6"
)

type AFConfigData struct {
	Key         AFConfigKey `json:"key,omitempty"`
	Hash        string      `json:"hash,omitempty"`
	Data        []any       `json:"data,omitempty"`
	SideChannel SideChannel `json:"sideChannel,omitempty"`
}

type SideChannel struct{}
